import { Button } from '@/components/ui/button'
import { Hash, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { useTranslations } from 'next-intl'

interface SlugFieldProps {
    value: string | undefined
    onChange: (value: string) => void
    onAutoGenerate?: () => void
    placeholder?: string
    id?: string
    isRequired?: boolean
    previewUrl?: string
    isDerived?: boolean
}

export function SlugField({
    value,
    onChange,
    onAutoGenerate,
    placeholder,
    id,
    isRequired = false,
    previewUrl,
    isDerived = false
}: SlugFieldProps) {
    const t = useTranslations('dynamicFields.slug')
    const [isFocused, setIsFocused] = useState(false)

    return (
        <div className="space-y-3">
            {!isDerived && (
                <div className="flex gap-2">
                    <div
                        className={`relative flex-1 transition-all duration-200 border rounded-xl overflow-hidden ${isFocused ? 'ring-2 border-zinc-900 ring-zinc-900/5' : 'border-zinc-200'
                            }`}
                    >
                        {/* Input Icon */}
                        <div className="absolute left-3 top-1/2 transform -translate-y-1/2 pointer-events-none">
                            <Hash className="h-4 w-4 text-zinc-400" />
                        </div>

                        <input
                            id={id}
                            type="text"
                            value={value || ''}
                            onChange={(e) => onChange(e.target.value)}
                            onFocus={() => setIsFocused(true)}
                            onBlur={() => setIsFocused(false)}
                            className="w-full pl-10 pr-4 py-2.5 bg-white text-sm font-mono tracking-tight focus:outline-none text-zinc-900"
                            placeholder={placeholder || 'url-slug'}
                            required={isRequired}
                        />
                    </div>

                    {onAutoGenerate && (
                        <Button
                            type="button"
                            variant="outline"
                            onClick={onAutoGenerate}
                            className="shrink-0 rounded-xl"
                            title={t('autoButton')}
                        >
                            <Sparkles className="h-4 w-4 mr-2" />
                            {t('autoButton')}
                        </Button>
                    )}
                </div>
            )}

            {previewUrl && (
                <div className={`flex items-center gap-2 px-4 py-3 rounded-xl border ${isDerived ? 'bg-blue-50/50 border-blue-100' : 'bg-zinc-50 border-zinc-100'}`}>
                    <div className={`p-1.5 rounded-lg ${isDerived ? 'bg-blue-100 text-blue-600' : 'bg-zinc-200 text-zinc-500'}`}>
                        <Sparkles className="h-3.5 w-3.5" />
                    </div>
                    <div className="min-w-0 flex-1">
                        <p className="text-[10px] uppercase tracking-wider font-bold text-zinc-400 mb-0.5">
                            {isDerived ? t('autoGenerated') : t('preview')}
                        </p>
                        <p className={`text-sm font-mono truncate ${isDerived ? 'text-blue-900 font-medium' : 'text-zinc-600'}`}>
                            {previewUrl}
                        </p>
                    </div>
                </div>
            )}

            {!isDerived && (
                <p className="text-xs text-zinc-500">
                    {t('hint')}
                </p>
            )}
        </div>
    )
}
