import type { Plugin } from '@/lib/plugins/config'

export const availablePlugins: Plugin[] = [
  {
    id: 's3',
    name: 'Amazon S3 Storage',
    description: 'Cloud storage with Amazon S3. Upload and manage files securely and scalably.',
    version: '1.0.0',
    category: 'utility',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '☁️',
    configurable: true,
  },
  {
    id: 'dynamic-nav',
    name: 'Dynamic TypePath Nav',
    description: 'Adds navigation items based on content types (typePath).',
    version: '1.0.0',
    category: 'ui',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '🧭',
    configurable: true,
  },
  {
    id: 'analytics',
    name: 'Google Analytics',
    description: 'Coming soon: Full integration with Google Analytics for advanced metrics.',
    version: '1.0.0',
    category: 'analytics',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '📊',
    configurable: false,
  },
  {
    id: 'email',
    name: 'Email Marketing',
    description: 'Coming soon: Email marketing system with templates and automation.',
    version: '1.0.0',
    category: 'integration',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '📧',
    configurable: false,
  },
  {
    id: 'cdn',
    name: 'CDN Integration',
    description: 'Coming soon: Content Delivery Network to optimize speed.',
    version: '1.0.0',
    category: 'utility',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '🌐',
    configurable: false,
  },
  {
    id: 'backup',
    name: 'Auto Backup',
    description: 'Coming soon: Scheduled automatic backups and restoration.',
    version: '1.0.0',
    category: 'security',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '💾',
    configurable: false,
  },
  {
    id: 'seo',
    name: 'SEO Optimizer',
    description: 'Coming soon: Advanced SEO optimization tools.',
    version: '1.0.0',
    category: 'utility',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '🔍',
    configurable: false,
  },
  {
    id: 'security',
    name: 'Security Shield',
    description: 'Coming soon: Advanced protection against threats and vulnerabilities.',
    version: '1.0.0',
    category: 'security',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '🛡️',
    configurable: false,
  },
  {
    id: 'social',
    name: 'Social Media',
    description: 'Coming soon: Social media integration and automatic publishing.',
    version: '1.0.0',
    category: 'integration',
    enabled: false,
    author: 'Nova CMS Team',
    icon: '📱',
    configurable: false,
  },
]
